### ISSUE TITLE
Need help understanding the proper steps.

### ISSUE THREAD

**Issue by JHDSonline** [GregBrimble/tailwindui-crawler-action#10]
When using this action do i first need to Run the crawler on my local files and have everything Pulled down and working including the .env file. Then upload to the repository created for this and then i can run the action? 

Im a bit lost when reading the instructions on both pages for the crawler and this action. 

Same goes for the crawler is it best to fork from the main site, or clone. Then Pull to my local and run the crawler, then update the repo with the full tailwind ui site, then run the action?

You guys are awesome by the way. Tailwind UI even told me in our correspondence when i requested a git,  to use the crawler and your action. 

So keep up the great work and thank you for everything you have done.

**Comment by GregBrimble** [comment]
Hi @JHDSonline ! If you're just after a private GitHub repository which is kept in sync with the TailwindUI site, all you need is this Action. This Action will use [kiliman's TailwindUI Crawler](https://github.com/kiliman/tailwindui-crawler) to periodically update your repository. Just follow [these instructions](https://github.com/GregBrimble/tailwindui-crawler-action#usage), and you should be good to go. Let me know if anything is unclear! The one common 'gotcha' is that new repositories now use the `main` branch, so you need to specify that with the `branch` and `current_branch` options.

If, however, you only want to take a copy of the TailwindUI components to a local folder, you can use the crawler directly with [these instructions](https://github.com/kiliman/tailwindui-crawler#-how-to-use).

**Comment by JHDSonline** [comment]
You rock thank you so much.
