### ISSUE TITLE
Trouble running the code after crawler action completes

### ISSUE THREAD

**Issue by connecteev** [GregBrimble/tailwindui-crawler-action#7]
This is probably a dumb question, but after the tailwindui action completes its task, checks the code into your github private repo, sends a notification etc, what's next?

How do you go from the code that is checked in, to something that is actually running and working on your localhost? The https://github.com/kiliman/tailwindui-crawler/ repo allows you to specify transformers, a tailwind prefix (very important for me), etc. 

1. How do you specify an .env file with the following settings?
```
BUILDINDEX=1
HTMLMODE=alpine
TRANSFORMERS=addTailwindCss,prefixSrc,useInter,prefixClasses,convertVue,stripAlpine
VUE_OUTPUT=$OUTPUT/vue
STRIPALPINE_OUTPUT=$OUTPUT/no-alpine

# prefixClasses
PREFIXCLASSES_PREFIX=tw-

```

2. How do you get the code working? Do you create a package.json? An .env file? A tailwind.js config file? What steps do you take to get this actually running perfectly on your localhost?

Thanks @GregBrimble

**Comment by GregBrimble** [comment]
Hi @connecteev ,

If you're running the action from within the repository that you're dumping TailwindUI into, you should be able to just add the `.env` file to the root of that repository, and it'll automatically pull it in and run the crawler with that.

Then, if you just clone your repository, and `npx serve`, it'll serve up the HTML viewer.

**Comment by connecteev** [comment]
@GregBrimble thanks for the tip! I'm a bit confused about the workflow, as I've basically cloned your repo and am running it as a standalone.
1. The action runs on schedule and checks for changes (either the kiliman crawler on tailwindui.com?)
2. If changes detected, it runs the kiliman crawler on tailwindui.com
3. it checks the code into my github repo

Now, a few hrs later, I get an email from the github action that some new code has been checked in. Where does my local setup and .env file come in? Is this what I would do next?
1. run "git pull" to get latest changes from my github repo
2. manually create a .env file in the root of that repo
3. run npx serve

I did do all of these, and it's not working. Here are some screenshots of what I am seeing:
1. going to http://localhost:5000 : https://www.webpagescreenshot.info/#v2=MBY24dnQH
2. going to http://localhost:5000/components/application-ui/forms/sign-in-forms/simple_card: https://www.webpagescreenshot.info/#v2=jbsF_XpQw

Clearly I'm missing something here..

**Comment by GregBrimble** [comment]
Ah, okay, I think I see.

So, you shouldn't need to clone this repo at all.

To start fresh:

1. Create a new private repo. Let's call it `tailwind`.
1. Add a [tailwind-crawler compatible `.env` file](https://github.com/kiliman/tailwindui-crawler/#%EF%B8%8F-example-env-file) to the root of the repo e.g.:

    ```sh
    HTMLMODE=alpine
    BUILDINDEX=1
    
    TRANSFORMERS=addTailwindCss,prefixSrc,useInter,changeColor,convertReact,stripAlpine
    
    # convertReact
    CONVERTREACT_OUTPUT=$OUTPUT/react
    
    # stripAlpine
    STRIPALPINE_OUTPUT=$OUTPUT/no-alpine
    
    # changeColor
    CHANGECOLOR_TO=red
    ```
    Do not include `EMAIL` or `PASSWORD`.

1. [Add `TAILWINDUI_EMAIL` and `TAILWINDUI_PASSWORD` secrets to the GitHub repository](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets).
1. Add the `.github/workflows/default.yml` file:

    ```yml
    name: Update
    on:
      schedule:
        - cron: "0 0 * * *" # Every day at midnight
    
    jobs:
      update:
        name: Update
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Run crawler
            uses: gregbrimble/tailwindui-crawler-action@v1.0.0
            with:
              email: ${{ secrets.TAILWINDUI_EMAIL }}
              password: ${{ secrets.TAILWINDUI_PASSWORD }}
    ```

    Don't change anything.
1. Subscribe to [email notifications for the repo](https://help.github.com/en/github/administering-a-repository/about-email-notifications-for-pushes-to-your-repository#enabling-email-notifications-for-pushes-to-your-repository).
1. Clone the repo locally.
1. Just after midnight, you should receive an email notification about the latest commit.
1. Locally, on your machine, `git pull`.
1. And now, `npx serve`. Your `.env` file configuration should have been applied at crawl-time:

    ![image](https://user-images.githubusercontent.com/8484333/82079462-cb88d280-96da-11ea-9077-5d2440cd8940.png)
    
    ![image](https://user-images.githubusercontent.com/8484333/82079508-de9ba280-96da-11ea-91e5-66247c22aea2.png)

    ![image](https://user-images.githubusercontent.com/8484333/82079550-eeb38200-96da-11ea-9b2f-846440389e2d.png)

I've just followed the steps above, so it should all work 🤞although I cheated slightly by adding `push` to my GitHub Action to trigger a crawl immediately:

```diff
    name: Update
    on:
+     push:
      schedule:
        - cron: "0 0 * * *" # Every day at midnight
```

Let me know if this works!

**Comment by GregBrimble** [comment]
Obviously, going forward, every time you get an email notification, you'll just need to `git pull` again, and you'll have the latest version to then `npx serve` up :)

**Comment by connecteev** [comment]
@GregBrimble thanks, this is helpful in clearing things up.
Btw these instructions are far superior to https://github.com/GregBrimble/tailwindui-crawler-action#usage (Step 3: "Optionally create a .env file with additional settings for the crawler." had me confused)

I followed all the steps, here's what I see:
1. The Main page looks great: http://localhost:5000/
https://www.webpagescreenshot.info/#v2=QXGpcmiSB
2. However, the rest of the pages look broken...any idea? I know this probably falls outside the scope of this "action" and more into the kiliman-crawler territory, but wondering if you're able to spot something off.
Screenshots: 
- https://www.webpagescreenshot.info/#v2=3S7WF3he-
- https://www.webpagescreenshot.info/#v2=xOuZUmwkY

.env file (note that it doesn't create a "tailwindui_output" folder, I dont see it in my repo)
```
OUTPUT=./tailwindui_output
BUILDINDEX=1
HTMLMODE=alpine
TRANSFORMERS=addTailwindCss,prefixSrc,useInter,prefixClasses,convertVue,stripAlpine
VUE_OUTPUT=$OUTPUT/vue
STRIPALPINE_OUTPUT=$OUTPUT/no-alpine

# addTailwindCss. This setting is needed if you have prefixClasses enabled
# Note: This config file does not get auto-generated. Please make sure it already exists.
ADDTAILWINDCSS_URL=/tailwind.css

# prefixClasses
PREFIXCLASSES_PREFIX=tw-
```

**Comment by GregBrimble** [comment]
Did you first try with the `.env` file I gave as an example? If we can get it working with that, it'll determine if whether it's the action's fault, or the crawler's.

Could you possibly share the repository with me, so I can take a look?

**Comment by connecteev** [comment]
@GregBrimble I tried your .env file with the same result. Just invited you to the repo, please feel free to make commits and interested in what you find..

**Comment by GregBrimble** [comment]
Hi @connecteev ,

Thanks! I just cloned it, ran `npx serve`, and it seems to work for me!

Navigating to http://localhost:5000/components/application-ui/forms/sign-in-forms/simple_card gives me the following:

![image](https://user-images.githubusercontent.com/8484333/82126448-d6a83500-97a4-11ea-9f5c-34f10e7ea520.png)

**So, a couple of things to check**:

- Are you running in a browser which is blocking access to the third-party external resources? Do you have any interfering extensions? Does your network tab show something similar?

    <img width="755" alt="image" src="https://user-images.githubusercontent.com/8484333/82126504-1f5fee00-97a5-11ea-86a3-14f9140a4a3b.png">

- If you run the [tailwind crawler](https://github.com/kiliman/tailwindui-crawler) locally, and `npx serve` the output directory, and open it in the same browser, does it work?

**Comment by connecteev** [comment]
@GregBrimble this is what I see in my network tab. I will try it out with the tailwind crawler locally as well.

![image](https://user-images.githubusercontent.com/64816/82126667-f3bc1400-9762-11ea-86e5-958dfbbf8e92.png)

**Comment by connecteev** [comment]
@GregBrimble it works fine if I use https://github.com/kiliman/tailwindui-crawler/
with these instructions:
```
Clone https://github.com/kiliman/tailwindui-crawler

Run:
$ cd crawler
$ yarn

Then create a .env file with your tailwindUI email, password, and optional output folder.

From tailwindui_crawler_kiliman/crawler, run command:
$ yarn start

From $OUTPUT (tailwindui_crawler_kiliman/tailwindui_output) folder, run command:
$ yarn global add serve
$ cd tailwindui_output
$ serve
```

![image](https://user-images.githubusercontent.com/64816/82126772-a2f8eb00-9763-11ea-9f8a-da73ce75fd49.png)

**Comment by GregBrimble** [comment]
Okay, looks like there's an issue fetching the Tailwind CSS, which makes sense, given the lack of styling on your page. Odd that you're trying to fetch a different filename: `tailwind.css` vs. `tailwind.min.css`. On [the source of that page](https://github.com/connecteev/tailwindui_clone/blob/master/components/application-ui/forms/sign-in-forms/simple_card.html#L6), you can see that the CSS should be fetched from the CDN.

Did you try in a different browser?

Can you also try disabling the cache (image below), and trying a forced refresh (Ctrl/⌘ + F5/R)? I wonder if the HTML content is outdated?

![image](https://user-images.githubusercontent.com/8484333/82126820-1112d180-97a7-11ea-96cf-9b1cf083405f.png)

**Comment by connecteev** [comment]
@GregBrimble just tried disabling chrome cache, cleared application data, and seeing the same result. The same result with firefox as well, so it's not a cache or browser issue.

Btw, when serving the tailwindui_clone repo (that uses this action), none of these 2 files exist in tailwindui_clone:
http://localhost:5000/tailwind.css
http://localhost:5000/tailwind.min.css

But http://localhost:5000/tailwind.css exists if I use the kiliman repo version..
As an aside, did you try clearing _your_ cache? I suspect it works for you because it's taking the .css file from when you served your own repo...when the file actually doesn't exist in my repo (no idea why).

Thinking aloud...what step is missing that creates the tailwind.css file?

**Comment by GregBrimble** [comment]
Ah, I see now!

```sh
ADDTAILWINDCSS_URL=/tailwind.css
```

You have this config in your `.env`. Remove it, and it should just use the CDN instead :)

**Comment by connecteev** [comment]
@GregBrimble thanks. I cant use the CDN though. A big reason I am using the kiliman crawler is for appending the tw- prefixClasses. That setting isn't working,

```
TRANSFORMERS=addTailwindCss,prefixSrc,useInter,convertVue,convertReact,stripAlpine,prefixClasses
PREFIXCLASSES_PREFIX=tw-
```

It works in the kiliman repo, though..which is strange.

Now, still trying to get my .env file (copied above) to work...

**Comment by connecteev** [comment]
@GregBrimble any idea why the action doesnt create a tailwind.css file, but kiliman's crawler does?
Here's the .env file I am trying to get working again:

```
BUILDINDEX=1
HTMLMODE=alpine

TRANSFORMERS=addTailwindCss,prefixSrc,useInter,convertVue,convertReact,stripAlpine,prefixClasses

CONVERTREACT_OUTPUT=$OUTPUT/react
VUE_OUTPUT=$OUTPUT/vue
STRIPALPINE_OUTPUT=$OUTPUT/no-alpine

# addTailwindCss. This setting is needed if you have prefixClasses enabled
ADDTAILWINDCSS_URL=./tailwind.css

# prefixClasses
PREFIXCLASSES_PREFIX=tw-
```

**Comment by GregBrimble** [comment]
I personally don't need a custom CSS file, so don't know much about how (or if) kiliman's crawler creates one. Have you tried simply copying the `tailwind.css` file into the root of your repo? If it's trying to serve that file, and you just add one that works, hopefully it'll just work?

If you want to add a custom build config so the CSS file is built dynamically, you'll need to set that up as another step in your GitHub Action workflow, which is out-of-scope of this action.

**Comment by connecteev** [comment]
@GregBrimble thanks for the help
just trying to understand this action better and compare against the commands kilman's code runs...they are not the same. 

Where does this crawler/index.js file come from?
https://github.com/GregBrimble/tailwindui-crawler-action/blob/f40d23da58140d1271bea395736fd3bf6b3338d3/entrypoint.sh#L54

**Comment by GregBrimble** [comment]
No problem!

We first [clone the crawler repo](https://github.com/GregBrimble/tailwindui-crawler-action/blob/f40d23da58140d1271bea395736fd3bf6b3338d3/entrypoint.sh#L8-L21) into `/crawler`, and then we're just running the main entrypoint of the crawler: `index.js`.

**Comment by connecteev** [comment]
Thanks! I did try [this](https://github.com/connecteev/tailwindui-crawler-action/commit/7a4ffa264872beb2da046d6a1bdb5e743c181f13) but that didnt help either.

**Comment by GregBrimble** [comment]
Ah, looks like it the crawler doesn't generate the custom CSS file. You'll need to create this yourself, either manually, or as part of the action, (e.g. using PostCSS).

**Comment by connecteev** [comment]
@GregBrimble will do, thanks

**Comment by connecteev** [comment]
Hi @GregBrimble it would be really neat if this issue could be fixed. Perhaps you'd be willing to spend a few minutes to take a look at why this repo is not generating a custom CSS file? It does look like the kiliman repo is when you run the commands...appreciate your eyes on this, thanks in advance!
