### ISSUE TITLE
Tailwindui crawler build broken

### ISSUE THREAD

**Issue by connecteev** [GregBrimble/tailwindui-crawler-action#8]
@GregBrimble sorry to bug you with this one, but any idea why I have started seeing this?
https://www.webpagescreenshot.info/#v2=N-abp_ZUC

The error shows
```
  ##[error]fatal: repository 'https://github.com/connecteev/tailwindui_clone/' not found
  ##[error]The process '/usr/bin/git' failed with exit code 128
```
but clearly the repository exists (and you've been invited to it). Maybe a github glitch...are you experiencing anything like this, or does your build work?

**Comment by GregBrimble** [comment]
Hi @connecteev ,

Looks like GitHub are having issues at the moment: https://www.githubstatus.com.

Specifically, someone has made an issue for the @actions/checkout action: https://github.com/actions/checkout/issues/254.

Hopefully they fix things soon :)

**Comment by connecteev** [comment]
hi @GregBrimble thanks for the link! actions/checkout#254 is exactly what I am experiencing. Let's wait and see :) Thanks!
