### ISSUE TITLE
Crawler Issue

### ISSUE THREAD

**Issue by entity** [GregBrimble/tailwindui-crawler-action#9]
Morning Greg,

Really appreciate the swift response yesterday to update the action, just tried running and get the following:
```
Running crawler...
/crawler/index.js:116
  if ($elem.attr('class')?.length > 0 && !$elem.attr('_style')) return $elem
                          ^

SyntaxError: Unexpected token '.'
    at Object.compileFunction (vm.js:344:18)
    at wrapSafe (internal/modules/cjs/loader.js:1048:15)
    at Module._compile (internal/modules/cjs/loader.js:1082:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Commiting changes...
On branch master
Your branch is up to date with 'origin/master'.
```

Any reason for this?

**Comment by GregBrimble** [comment]
This is because it's running in Node.js 13 rather than 14 (no optional chaining support). The latest version 1.1.0 *should* have upgraded this. Are you definitely running v1.1.0?

**Comment by entity** [comment]
Weirdly, the only fix was to make a new repo.. odd haha.

Will close as _technically_ not a bug, may be just a weird thing Github side?

**Comment by GregBrimble** [comment]
I tested myself yesterday with an old repo, and things just worked as expected for me. If you grab your the log of you Action executing, you might see the version of my crawler action that you're pulling? I think it's maybe just cached or something, like you say, a GitHub quirk.

**Comment by entity** [comment]
Yeah, it's strange aha - only thing currently is no Alpine showing, but did mention in https://github.com/kiliman/tailwindui-crawler/issues/46#issuecomment-820987121 👍
